# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, folder_id: str=None):  # noqa: E501
        """ListResponse - a model defined in Swagger

        :param id: The id of this ListResponse.  # noqa: E501
        :type id: str
        :param name: The name of this ListResponse.  # noqa: E501
        :type name: str
        :param folder_id: The folder_id of this ListResponse.  # noqa: E501
        :type folder_id: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'folder_id': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'folder_id': 'folder_id'
        }
        self._id = id
        self._name = name
        self._folder_id = folder_id

    @classmethod
    def from_dict(cls, dikt) -> 'ListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListResponse of this ListResponse.  # noqa: E501
        :rtype: ListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ListResponse.

        Unique ID of the list  # noqa: E501

        :return: The id of this ListResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ListResponse.

        Unique ID of the list  # noqa: E501

        :param id: The id of this ListResponse.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ListResponse.

        Name of the list  # noqa: E501

        :return: The name of this ListResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ListResponse.

        Name of the list  # noqa: E501

        :param name: The name of this ListResponse.
        :type name: str
        """

        self._name = name

    @property
    def folder_id(self) -> str:
        """Gets the folder_id of this ListResponse.

        ID of the folder where the list belongs  # noqa: E501

        :return: The folder_id of this ListResponse.
        :rtype: str
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id: str):
        """Sets the folder_id of this ListResponse.

        ID of the folder where the list belongs  # noqa: E501

        :param folder_id: The folder_id of this ListResponse.
        :type folder_id: str
        """

        self._folder_id = folder_id
