openapi: 3.0.0
info:
  title: Sending API
  description: "API for sending individual and bulk messages, and managing messages\
    \ efficiently."
  contact:
    name: API Support
    email: support@example.com
  version: "1.1"
servers:
- url: http://localhost:8080
  description: Local development server
- url: https://api.sending.com
  description: Production server
paths:
  /send/individual:
    post:
      tags:
      - Sending
      summary: Send an individual message
      description: Sends a personalized message to a single recipient.
      operationId: send_individual_message
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendIndividualRequest'
        required: true
      responses:
        "200":
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
        "400":
          description: Invalid input or missing fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-openapi-router-controller: swagger_server.controllers.sending_controller
components:
  schemas:
    SendIndividualRequest:
      required:
      - message
      - sender_email
      - sender_name
      - subject
      - to_email
      - to_name
      type: object
      properties:
        to_email:
          type: string
          description: Email address of the recipient
          format: email
        to_name:
          type: string
          description: Name of the recipient
        message:
          type: string
          description: Content of the message
        sender_email:
          type: string
          description: Sender's email address
          format: email
        sender_name:
          type: string
          description: Name of the sender
        subject:
          type: string
          description: Subject of the email
    SendResponse:
      type: object
      properties:
        status:
          type: string
          example: Message sent successfully
        send_id:
          type: string
          description: Unique identifier for the sent message
      example:
        send_id: send_id
        status: Message sent successfully
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
          example: Bad request

